# Import one income statement

In [2]:
"""Try to get qurterly reports into dataframe"""
import pandas as pd
import numpy as np 
import yfinance as yf 
from yahoofinancials import YahooFinancials
import datetime as dt

# import data
yahoo_financials = YahooFinancials('AAPL')
data = yahoo_financials.get_financial_stmts('quarterly', 'income')
# Drill down in dictionary to get the data we want 
dict_list = data['incomeStatementHistoryQuarterly']['AAPL']
# Create the dataframe
df = pd.concat([pd.DataFrame(i) for i in dict_list], axis=1)
# Sort Columns 
df = df.reindex(sorted(df.columns), axis=1)
# rename the index
df = df.rename_axis('name_of_metric').reset_index()
df

,name_of_metric,2022-03-31,2022-06-30,2022-09-30,2022-12-31
0,basicAverageShares,1.627880e+10,1.616294e+10,1.603038e+10,1.589272e+10
1,basicEPS,1.540000e+00,1.200000e+00,1.290000e+00,1.890000e+00
2,costOfRevenue,5.471900e+10,4.707400e+10,5.205100e+10,6.682200e+10
3,dilutedAverageShares,1.640332e+10,1.626220e+10,1.611846e+10,1.595572e+10
4,dilutedEPS,1.520000e+00,1.200000e+00,1.290000e+00,1.880000e+00
5,dilutedNIAvailtoComStockholders,2.501000e+10,1.944200e+10,2.072100e+10,9.517100e+10
6,eBITDA,NaN,NaN,NaN,1.280480e+11
7,ebit,3.083000e+10,2.378500e+10,2.548400e+10,3.662600e+10
8,grossProfit,4.255900e+10,3.588500e+10,3.809500e+10,1.668710e+11
9,interestExpense,6.910000e+08,7.190000e+08,8.270000e+08,3.240000e+09
10,interestExpenseNonOperating,6.910000e+08,7.190000e+08,8.270000e+08,3.240000e+09
11,interestIncome,7.000000e+08,7.220000e+08,7.530000e+08,8.680000e+08
12,interestIncomeNonOperating,7.000000e+08,7.220000e+08,7.530000e+08,3.043000e+09
13,netIncome,2.501000e+10,1.944200e+10,2.072100e+10,9.517100e+10
14,netIncomeCommonStockholders,2.501000e+10,1.944200e+10,2.072100e+10,9.517100e+10
15,netIncomeContinuousOperations,2.501000e+10,1.944200e+10,2.072100e+10,2.999800e+10
16,netIncomeFromContinuingAndDiscontinuedOperation,2.501000e+10,1.944200e+10,2.072100e+10,9.517100e+10
17,netIncomeFromContinuingOperationNetMinorityInt...,2.501000e+10,1.944200e+10,2.072100e+10,2.999800e+10
18,netIncomeIncludingNoncontrollingInterests,2.501000e+10,1.944200e+10,2.072100e+10,2.999800e+10
19,netInterestIncome,9.000000e+06,3.000000e+06,-7.400000e+07,-1.970000e+08
20,netNonOperatingInterestIncomeExpense,9.000000e+06,3.000000e+06,-7.400000e+07,-1.970000e+08
21,normalizedEBITDA,3.356700e+10,2.659000e+10,2.834900e+10,3.954200e+10
22,normalizedIncome,2.501000e+10,1.944200e+10,2.072100e+10,2.999800e+10
23,operatingExpense,1.258000e+10,1.280900e+10,1.320100e+10,1.431600e+10
24,operatingIncome,2.997900e+10,2.307600e+10,2.489400e+10,1.139650e+11
25,operatingRevenue,9.727800e+10,8.295900e+10,9.014600e+10,1.171540e+11
26,otherIncomeExpense,1.510000e+08,-1.300000e+07,-1.630000e+08,-2.830000e+08
27,otherNonOperatingIncomeExpenses,1.510000e+08,-1.300000e+07,-1.630000e+08,-2.580000e+08
28,pretaxIncome,3.013900e+10,2.306600e+10,2.465700e+10,1.134850e+11
29,reconciledCostOfRevenue,5.471900e+10,4.707400e+10,5.205100e+10,2.206660e+11
30,reconciledDepreciation,2.737000e+09,2.805000e+09,2.865000e+09,2.916000e+09
31,researchAndDevelopment,6.387000e+09,6.797000e+09,6.761000e+09,7.709000e+09
32,sellingGeneralAndAdministration,6.193000e+09,6.012000e+09,6.440000e+09,6.607000e+09
33,taxEffectOfUnusualItems,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
34,taxProvision,5.129000e+09,3.624000e+09,3.936000e+09,1.831400e+10
35,taxRateForCalcs,1.700000e-01,1.570000e-01,1.596300e-01,1.613780e-01
36,totalExpenses,6.729900e+10,5.988300e+10,6.525200e+10,8.113800e+10
37,totalOperatingIncomeAsReported,2.997900e+10,2.307600e+10,2.489400e+10,3.601600e+10
38,totalRevenue,9.727800e+10,8.295900e+10,9.014600e+10,3.875370e+11

# import a balance sheet

In [3]:
# import data
yahoo_financials = YahooFinancials('AAPL')
data = yahoo_financials.get_financial_stmts('quarterly', 'balance')
# Drill down in dictionary to get the data we want 
dict_list = data['balanceSheetHistoryQuarterly']['AAPL']
# Create the dataframe
df = pd.concat([pd.DataFrame(i) for i in dict_list], axis=1)
# Sort Columns 
df = df.reindex(sorted(df.columns), axis=1)
# rename the index
df = df.rename_axis('name_of_metric').reset_index()
df

,name_of_metric,2022-03-31,2022-06-30,2022-09-30,2022-12-31
0,accountsPayable,5.268200e+10,4.834300e+10,6.411500e+10,5.791800e+10
1,accountsReceivable,2.081500e+10,2.180300e+10,2.818400e+10,2.375200e+10
2,accumulatedDepreciation,-7.002000e+10,-7.151600e+10,-7.234000e+10,-6.804400e+10
3,availableForSaleSecurities,1.412190e+11,1.310770e+11,1.208050e+11,NaN
4,capitalStock,6.118100e+10,6.211500e+10,6.484900e+10,6.639900e+10
5,cashAndCashEquivalents,2.809800e+10,2.750200e+10,2.364600e+10,2.053500e+10
6,cashCashEquivalentsAndShortTermInvestments,5.151100e+10,4.823100e+10,4.830400e+10,5.135500e+10
7,cashEquivalents,1.380000e+10,1.465000e+10,5.100000e+09,2.627000e+09
8,cashFinancial,1.429800e+10,1.285200e+10,1.854600e+10,1.790800e+10
9,commercialPaper,6.999000e+09,1.098200e+10,9.982000e+09,1.743000e+09
10,commonStock,6.118100e+10,6.211500e+10,6.484900e+10,6.639900e+10
11,commonStockEquity,6.739900e+10,5.810700e+10,5.067200e+10,5.672700e+10
12,currentAssets,1.181800e+11,1.122920e+11,1.354050e+11,1.287770e+11
13,currentDebt,1.665800e+10,2.499100e+10,2.111000e+10,1.148300e+10
14,currentDebtAndCapitalLeaseObligation,1.665800e+10,2.499100e+10,2.111000e+10,1.148300e+10
15,currentDeferredLiabilities,7.920000e+09,7.728000e+09,7.912000e+09,7.992000e+09
16,currentDeferredRevenue,7.920000e+09,7.728000e+09,7.912000e+09,7.992000e+09
17,currentLiabilities,1.275080e+11,1.298730e+11,1.539820e+11,1.372860e+11
18,gainsLossesNotAffectingRetainedEarnings,-6.494000e+09,-9.297000e+09,-1.110900e+10,-1.291200e+10
19,grossPPE,1.093240e+11,1.118510e+11,1.144570e+11,1.109950e+11
20,inventory,5.460000e+09,5.433000e+09,4.946000e+09,6.820000e+09
21,investedCapital,1.873800e+11,1.777980e+11,1.707410e+11,1.678370e+11
22,investmentinFinancialAssets,1.412190e+11,1.310770e+11,1.208050e+11,NaN
23,investmentsAndAdvances,1.412190e+11,1.310770e+11,1.208050e+11,1.140950e+11
24,longTermDebt,1.033230e+11,9.470000e+10,9.895900e+10,9.962700e+10
25,longTermDebtAndCapitalLeaseObligation,1.033230e+11,9.470000e+10,9.895900e+10,9.962700e+10
26,netDebt,9.188300e+10,9.218900e+10,9.642300e+10,9.057500e+10
27,netPPE,3.930400e+10,4.033500e+10,4.211700e+10,4.295100e+10
28,netTangibleAssets,6.739900e+10,5.810700e+10,5.067200e+10,5.672700e+10
29,ordinarySharesNumber,1.620757e+10,1.609538e+10,1.594342e+10,1.584241e+10
30,otherCurrentAssets,1.580900e+10,1.638600e+10,2.122300e+10,1.642200e+10
31,otherCurrentBorrowings,9.659000e+09,1.400900e+10,1.112800e+10,9.740000e+09
32,otherCurrentLiabilities,5.024800e+10,4.881100e+10,6.084500e+10,5.989300e+10
33,otherInvestments,1.412190e+11,1.310770e+11,1.208050e+11,1.140950e+11
34,otherNonCurrentAssets,5.195900e+10,5.260500e+10,5.442800e+10,6.092400e+10
35,otherNonCurrentLiabilities,3.172100e+10,3.293000e+10,3.248500e+10,5.310700e+10
36,otherReceivables,2.458500e+10,2.043900e+10,3.274800e+10,3.042800e+10
37,otherShortTermInvestments,2.341300e+10,2.072900e+10,2.465800e+10,3.082000e+10
38,payables,5.268200e+10,4.834300e+10,6.411500e+10,5.791800e+10
39,payablesAndAccruedExpenses,5.268200e+10,4.834300e+10,6.411500e+10,5.791800e+10
40,receivables,4.540000e+10,4.224200e+10,6.093200e+10,5.418000e+10
41,retainedEarnings,1.271200e+10,5.289000e+09,-3.068000e+09,3.240000e+09
42,shareIssued,1.620757e+10,1.609538e+10,1.594342e+10,1.584241e+10
43,stockholdersEquity,6.739900e+10,5.810700e+10,5.067200e+10,5.672700e+10
44,tangibleBookValue,6.739900e+10,5.810700e+10,5.067200e+10,5.672700e+10
45,totalAssets,3.506620e+11,3.363090e+11,3.527550e+11,3.467470e+11
46,totalCapitalization,1.707220e+11,1.528070e+11,1.496310e+11,1.563540e+11
47,totalDebt,1.199810e+11,1.196910e+11,1.200690e+11,1.111100e+11
48,totalEquityGrossMinorityInterest,6.739900e+10,5.810700e+10,5.067200e+10,5.672700e+10
49,totalLiabilitiesNetMinorityInterest,2.832630e+11,2.782020e+11,3.020830e+11,2.900200e+11
50,totalNonCurrentAssets,2.324820e+11,2.240170e+11,2.173500e+11,2.179700e+11
51,totalNonCurrentLiabilitiesNetMinorityInterest,1.557550e+11,1.483290e+11,1.481010e+11,1.527340e+11
52,tradeandOtherPayablesNonCurrent,2.071100e+10,2.069900e+10,1.665700e+10,NaN
53,workingCapital,-9.328000e+09,-1.758100e+10,-1.857700e+10,-8.509000e+09
54,landAndImprovements,NaN,NaN,2.212600e+10,NaN
55,leases,NaN,NaN,1.127100e+10,NaN
56,machineryFurnitureEquipment,NaN,NaN,8.106000e+10,NaN
57,properties,NaN,NaN,0.000000e+00,NaN
58,finishedGoods,NaN,NaN,NaN,4.307000e+09
59,rawMaterials,NaN,NaN,NaN,2.513000e+09

# import cash flow

In [7]:
# import data
yahoo_financials = YahooFinancials('AAPL')
data = yahoo_financials.get_financial_stmts('quarterly', 'cash')
# Drill down in dictionary to get the data we want 
dict_list = data['cashflowStatementHistoryQuarterly']['AAPL']
# print(data)
# Create the dataframe
df = pd.concat([pd.DataFrame(i) for i in dict_list], axis=1)
# Sort Columns 
df = df.reindex(sorted(df.columns), axis=1)
# rename the index
df = df.rename_axis('name_of_metric').reset_index()
df

,name_of_metric,2022-03-31,2022-06-30,2022-09-30,2022-12-31
0,beginningCashPosition,3.863000e+10,2.918000e+10,2.886100e+10,2.497700e+10
1,capitalExpenditure,-2.514000e+09,-2.102000e+09,-3.289000e+09,-1.169200e+10
2,cashDividendsPaid,-3.595000e+09,-3.811000e+09,-3.703000e+09,-1.487700e+10
3,cashFlowFromContinuingFinancingActivities,-2.835100e+10,-2.744500e+10,-2.679400e+10,-1.181530e+11
4,cashFlowFromContinuingInvestingActivities,-9.265000e+09,4.234000e+09,-1.217000e+09,-1.445000e+09
5,cashFlowFromContinuingOperatingActivities,2.816600e+10,2.289200e+10,2.412700e+10,1.091900e+11
6,changeInAccountPayable,-2.156300e+10,-4.358000e+09,1.555600e+10,-1.644000e+10
7,changeInCashSupplementalAsReported,-9.450000e+09,-3.190000e+08,-3.884000e+09,-1.665600e+10
8,changeInInventory,3.840000e+08,-1.600000e+07,4.350000e+08,-1.004000e+09
9,changeInOtherCurrentAssets,1.379000e+09,2.530000e+08,-3.210000e+09,-4.099000e+09
10,changeInOtherCurrentLiabilities,-2.348000e+09,-1.902000e+09,5.646000e+09,5.154000e+09
11,changeInOtherWorkingCapital,1.650000e+08,-3.670000e+08,2.180000e+08,1.310000e+08
12,changeInPayable,-2.156300e+10,-4.358000e+09,1.555600e+10,-1.644000e+10
13,changeInPayablesAndAccruedExpense,-2.156300e+10,-4.358000e+09,1.555600e+10,-1.644000e+10
14,changeInReceivables,1.993100e+10,3.165000e+09,-1.869300e+10,6.595000e+09
15,changeInWorkingCapital,-2.052000e+09,-3.225000e+09,-4.800000e+07,-6.822000e+09
16,changesInAccountReceivables,9.476000e+09,-9.810000e+08,-6.384000e+09,4.275000e+09
17,changesInCash,-9.450000e+09,-3.190000e+08,-3.884000e+09,-3.003000e+09
18,commonStockDividendPaid,-3.595000e+09,-3.811000e+09,-3.703000e+09,-3.768000e+09
19,commonStockPayments,-2.263100e+10,-2.186500e+10,-2.442800e+10,-1.947500e+10
20,deferredIncomeTax,4.060000e+08,1.668000e+09,-1.861000e+09,NaN
21,deferredTax,4.060000e+08,1.668000e+09,-1.861000e+09,NaN
22,depreciationAmortizationDepletion,2.737000e+09,2.805000e+09,2.865000e+09,1.132300e+10
23,depreciationAndAmortization,2.737000e+09,2.805000e+09,2.865000e+09,2.916000e+09
24,endCashPosition,2.918000e+10,2.886100e+10,2.497700e+10,2.197400e+10
25,financingCashFlow,-2.835100e+10,-2.744500e+10,-2.679400e+10,-3.556300e+10
26,freeCashFlow,2.565200e+10,2.079000e+10,2.083800e+10,3.021800e+10
27,incomeTaxPaidSupplementalData,4.066000e+09,2.950000e+09,7.322000e+09,8.280000e+08
28,interestPaidSupplementalData,8.750000e+08,5.040000e+08,9.550000e+08,7.030000e+08
29,investingCashFlow,-9.265000e+09,4.234000e+09,-1.217000e+09,-7.693000e+09
30,longTermDebtPayments,-3.750000e+09,-3.000000e+09,-2.793000e+09,-1.401000e+09
31,netCommonStockIssuance,-2.263100e+10,-2.186500e+10,-2.442800e+10,-8.839900e+10
32,netIncome,2.501000e+10,1.944200e+10,2.072100e+10,9.517100e+10
33,netIncomeFromContinuingOperations,2.501000e+10,1.944200e+10,2.072100e+10,9.517100e+10
34,netInvestmentPurchaseAndSale,-6.390000e+09,6.953000e+09,2.806000e+09,2.483000e+09
35,netIssuancePaymentsOfDebt,-1.751000e+09,9.710000e+08,1.657000e+09,-9.615000e+09
36,netLongTermDebtIssuance,-3.750000e+09,-3.000000e+09,2.672000e+09,-1.401000e+09
37,netOtherFinancingCharges,-3.740000e+08,-2.740000e+09,-3.200000e+08,-2.705000e+09
38,netOtherInvestingChanges,-1.940000e+08,-6.150000e+08,-5.970000e+08,-1.410000e+08
39,netPPEPurchaseAndSale,-2.514000e+09,-2.102000e+09,-3.289000e+09,-1.169200e+10
40,netShortTermDebtIssuance,1.999000e+09,3.971000e+09,-1.015000e+09,-3.259000e+09
41,operatingCashFlow,2.816600e+10,2.289200e+10,2.412700e+10,3.400500e+10
42,otherNonCashItems,-1.870000e+08,-4.100000e+07,1.720000e+08,-1.055000e+09
43,purchaseOfInvestment,-2.707400e+10,-8.191000e+09,-6.745000e+09,-4.716300e+10
44,purchaseOfPPE,-2.514000e+09,-2.102000e+09,-3.289000e+09,-3.787000e+09
45,repaymentOfDebt,-3.750000e+09,-3.000000e+09,-2.793000e+09,-1.815800e+10
46,repurchaseOfCapitalStock,-2.263100e+10,-2.186500e+10,-2.442800e+10,-1.947500e+10
47,saleOfInvestment,2.068400e+10,1.514400e+10,9.551000e+09,7.636000e+09
48,stockBasedCompensation,2.252000e+09,2.243000e+09,2.278000e+09,9.678000e+09
49,issuanceOfDebt,NaN,3.971000e+09,4.950000e+08,NaN
50,longTermDebtIssuance,NaN,0.000000e+00,5.465000e+09,NaN
51,netBusinessPurchaseAndSale,NaN,-2.000000e+06,-1.370000e+08,NaN
52,purchaseOfBusiness,NaN,-2.000000e+06,-1.370000e+08,NaN
53,shortTermDebtIssuance,NaN,3.971000e+09,-1.015000e+09,NaN
54,shortTermDebtPayments,NaN,NaN,NaN,-8.214000e+09

# Turn into functions

In [8]:
def getIncomeStatement(ticker):
    """
        Function params: string ticker (the ticker of the company of choice)
        Returns: A data frame of the quartler income statement for the company
    """
    # import data
    yahoo_financials = YahooFinancials(ticker)
    data = yahoo_financials.get_financial_stmts('quarterly', 'income')
    # Drill down in dictionary to get the data we want 
    dict_list = data['incomeStatementHistoryQuarterly'][ticker]
    # Create the dataframe
    df = pd.concat([pd.DataFrame(i) for i in dict_list], axis=1)
    # Sort Columns 
    df = df.reindex(sorted(df.columns), axis=1)
    # rename the index
    df = df.rename_axis('name_of_metric').reset_index()
    return df
    
def getBalanceSheet(ticker):
    """
        Function params: string ticker (the ticker of the company of choice)
        Returns: A data frame of the quartler balance for the company 
    """
    # import data
    yahoo_financials = YahooFinancials(ticker)
    data = yahoo_financials.get_financial_stmts('quarterly', 'balance')
    # Drill down in dictionary to get the data we want 
    dict_list = data['balanceSheetHistoryQuarterly'][ticker]
    # Create the dataframe
    df = pd.concat([pd.DataFrame(i) for i in dict_list], axis=1)
    # Sort Columns 
    df = df.reindex(sorted(df.columns), axis=1)
    # rename the index
    df = df.rename_axis('name_of_metric').reset_index()
    return df

def getOneDayPrice(ticker, start_date, end_date):
    yahoo_financials = YahooFinancials(ticker)
    yahoo_financials.get_historical_price_data(start_date, end_date, time_interval='daily')
    df = pd.DataFrame(data[ticker]['prices'])
    df = df.drop('date', axis=1).set_index('formatted_date')
    #price = df['close'][date_of_interest]
    return df

# Create fns to calculate the metrics

In [9]:
# Price to earning ratio
def pe_ratio(earning_per_share, price):
    """
    Params: date_of_stmt (col name), ticker, earningPerShare value for the columns 
    Returns: PE Ratio 
    """
    # pe = 0
    # vals = (date_of_stmt).split('-')
    # string_date_of_stmt = date_of_stmt
    # start = dt.date(int(vals[0]), int(vals[1]), int(vals[2])-2)
    # date_of_stmt = dt.date(int(vals[0]), int(vals[1]), int(vals[2]))
    # end = dt.date(int(vals[0]), int(vals[1]), int(vals[2])+2)

    # yahoo_financials = YahooFinancials(ticker)
    # yahoo_financials.get_historical_price_data(start, end, time_interval='daily')
    # df = pd.DataFrame(data['AAPL']['prices'])
    # df = df.drop('date', axis=1).set_index('formatted_date')
    # price = df['close'][string_date_of_stmt]
    return price / earning_per_share

def price_book_ratio (net_assests, price): 
    return price/net_assests

# def free_cash_flow(cashFlowFromContinuingOperatingActivities, interestExpense):
#     """
#     cashFlowFromContinuingOperatingActivities from cash 
#     intestestExpense from income
#     """

SyntaxError: expected ':' (2922495174.py, line 24)